name: ci

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build-and-test:
    name: Build & Test (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.3"
          cache: true
          arch: win64_msvc2022_64

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure (CMake)
        run: cmake --preset windows-msvc

      - name: Build (CMake)
        run: cmake --build --preset windows-msvc --config Release

      - name: Run tests (CTest)
        run: ctest --preset windows-msvc -C Release --output-on-failure
